#ifndef RT_RT_ERRORS_H
# define RT_RT_ERRORS_H

# define ERR_INV_ARGS_NUM 5
# define ERR_INV_FILE 6

# define ERR_MALLOC 7

# define ERR_SDL_INIT 8
# define ERR_SDL_WIN 9
# define ERR_SDL_RENDER 10
# define ERR_SDL_TEXTURE_CREATE 11

# define ERR_USAGE 12
# define ERR_OPENCL 13
# define ERR_OPENCL_CLEAN 14
# define ERR_OPENCL_SETARG 15
# define ERR_OPENCL_GET_PLATFORM_ID 16
# define ERR_OPENCL_GET_DEVICE_ID 17
# define ERR_OPENCL_CREATE_CONTEXT 18
# define ERR_OPENCL_CREATE_QUEUE 19
# define ERR_OPENCL_CREATE_PROGRAM 20
# define ERR_OPENCL_BUILD_PROGRAM 21
# define ERR_OPENCL_CREATE_KERNEL 22
# define ERR_OPENCL_CREATE_BUFFER 23
# define ERR_OPENCL_RUN_KERNELS 24
# define ERR_OPENCL_READ_BUFFER 25
# define ERR_OPENCL_INV_SOURCE_CODE_FILE 26

# define ERR_INVALID_TEXRTURE_DIR 27

#endif
